app:
  name: "gofiber-skeleton"
  env: "development"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/dev/tls/zercle-dev.crt"
    priv: "./internal/assets/dev/tls/zercle-dev.key"
    ca: "./internal/assets/dev/tls/rootCA.crt"
    log: "./log"

db:
  mariadb:
    sock: "/var/run/mysqld/mysqld.sock"
    host: "localhost"
    port: 3306
    username: ""
    password: ""
    db_name: ""
    conn:
      min: 1
      max: 2
  postgres:
    sock: "/var/run/postgresql"
    host: "localhost"
    port: 5432
    username: ""
    password: ""
    db_name: ""
    conn:
      min: 1
      max: 2
  sqlite:
    db_name: "file:app.db?cache=shared"
  redis:
    host: "localhost"
    port: 6379
    username: ""
    password: ""
    db_name: 0

jwt:
  # openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
  private: "./internal/assets/dev/jwt/privkey.pem"
  # openssl ec -in privkey.pem -pubout -out pubkey.pem
  public: "./internal/assets/dev/jwt/pubkey.pem"
