app:
  name: "gofiber-skeleton"
  env: "production"
  port:
    http: 8080
    https: 8443
  path:
    cert: "./internal/assets/tls/zercle-prd.crt"
    priv: "./internal/assets/tls/zercle-prd.key"
    ca: "./internal/assets/tls/rootCA.crt"
    log: "./log"

db:
  mariadb:
    sock: "/var/run/mysqld/mysqld.sock"
    host: "localhost"
    port: 3306
    username: ""
    password: ""
    db_name: ""
    conn:
      min: 4
      max: 8
  postgres:
    sock: "/var/run/postgresql"
    host: "localhost"
    port: 5432
    username: ""
    password: ""
    db_name: ""
    conn:
      min: 4
      max: 8
  sqlite:
    db_name: "sqlite.db"
  redis:
    host: "localhost"
    port: 6379
    username: ""
    password: ""
    db_name: 0

jwt:
  # openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
  private: "./internal/assets/jwt/prd/privkey.pem"
  # openssl ec -in privkey.pem -pubout -out pubkey.pem
  public: "./internal/assets/jwt/prd/pubkey.pem"